project_id = "blrfypggmtatxlduvckc"

[functions.validate-invitation]
verify_jwt = false

[functions.start-invited-test]
verify_jwt = false

[functions.send-test-invitation]
verify_jwt = false

[functions.send-basic-test-invitation]
verify_jwt = false